### PR TITLE
Keep the centre consistent when size changes

### PR DESCRIPTION
**Pull request by shritekale**
Keeps the mapview center consistent when view bounds change.

### CODE REVIEW

**Comment by dhardiman** [comment]
LGTM

**Comment by shritekale** [comment]
Here it is..  :smile: 

rotate

**Comment by dhardiman** [comment]
Looks great.

**Comment by steveanthony** [comment]
Does this mean that if you're not looking at your current location, and you rotate the device, that you get taken back to your current location?

**Comment by dhardiman** [comment]
No. It's using the _centre_ location of the map, not the user's current location.

**Comment by shritekale** [comment]
Yep as @dhardiman mentioned, it wont.

**Comment by steveanthony** [comment]
Ah right, of course.

**Pull request merged**
