### PR TITLE
Don't wait for operations to finish

### PR DESCRIPTION
**Pull request by dhardiman**

### CODE REVIEW

**Comment by steveanthony** [comment]
Wasn't this added so that the tiles didn't try to constantly redraw?

**Comment by dhardiman** [comment]
No, it was added to try to prevent duplicate operations being added. But it's the wrong approach to deduping, and we solved the constant redraws elsewhere by tidying up the exit paths out of the tile fetch operation. All this was doing was blocking the rendering thread whilst the operation completed, thereby removing the point of pushing the fetches out to a different queue in the first place.

**Comment by steveanthony** [comment]
Fair enough.

**Comment by drhaynes** [comment]
LGTM!!! :-)

**Pull request merged**
